### ISSUE TITLE
Installing issue with FOSSEE Optimization Toolbox 

### ISSUE THREAD

**Issue by jitendra3109** [universecoder/FOSSEE_Bonmin#1]
@universecoder 
Could you help to install and up and running with FOSSEE Optimization Toolbox?
As I can you have experience with this tool.I actually went through the 
https://www.embotech.com/ECOS
https://github.com/embotech/ecos
but still, I do not find any clue about it and also not find much document about it.
Thank you.

**Comment by pranav-deshpande** [comment]
What exactly do you need to install? FOSSEE_Bonmin, the FOT toolbox here: https://atoms.scilab.org/toolboxes/FOT or ECOS? If it is one of the first two, where exactly are you facing difficulties?

**Comment by jitendra3109** [comment]
Thank you.

A conic problem has conic (nonlinear) constraints in addition to linear objective function and
linear constraints. Thus linear optimization is a special case of conic optimization.
ECOS is an open-source solver for computing solutions to conic optimization problems. Its
documentation and source code are available online.
But I did not much of above link so please : )

install ECOS source code (C API only) and compile the library

**Comment by pranav-deshpande** [comment]
Yes, I know what ECOS is. But I don't understand your last sentence 'But I did not much of above link so please'.

**Comment by jitendra3109** [comment]
Before doing  the task, this should be do 
Download and install ECOS source code (C API only) and compile the library. install
it locally in a suitable location. You should get `libecos.a' file. you will get  the output of executing the
'runecos' binary after the source code of ECOS is compiled.

So how ?

**Comment by pranav-deshpande** [comment]
Okay. So you are doing some task somewhere. I wonder why do you need that file though. Just clone the repository. Go to the required directory using the command line(use cd) and then type 'make'. After the build process is over; you will see the required files(libecos.a and runecos, along with several others) in the directory. And I hope that you are on some linux distro....

**Comment by jitendra3109** [comment]
Thanks.
This command I could not find anywhere related to ecos.
I run make command after that also ./runecosexp
so now How do I use it? Is that any example somewhere?

**Comment by jsroyal** [comment]
Thanks. 
Nice to meet you.
Can I get Whatsapp no so we can chat there?

**Comment by pranav-deshpande** [comment]
Follow this guide here: https://www.embotech.com/ECOS/How-to-use/C-API . Since from now on you will encounter ECOS specific issues, you should ask them on their github repository. You should read the README pdf as well.

**Comment by jitendra3109** [comment]
Thanks.
